name: dtool-lookup-webapp-build-and-test

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16']
    name: Node ${{ matrix.node-version }} 
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./dtool-lookup-webapp
        run: npm install

      - name: Lint
        working-directory: ./dtool-lookup-webapp
        run: npm run lint

      - name: Build
        working-directory: ./dtool-lookup-webapp
        run: npm run build

      # needs true tests first:
      # - name: Run tests
      #  working-directory: ./dtool-lookup-webapp
      #  run: npm test
